# PCA Demo
This demo illustrates how SIMBSIG can be used for Principal Component Analysis (PCA), and how the use compares to scikit-learn. 

In [1]:
# DELETE
# Mount your google drive in google colabfrom google.colab import drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
# DELETE
# Insert the directory
import sys
sys.path.insert(0,'/content/drive/MyDrive/simbsig/')
# Import worker classes
# from src.TestModule import TestClass
from simbsig.neighbors import PCA

In [3]:
# from simbsig.decomposition import PCA
from sklearn.decomposition import PCA as PCA_sk
import h5py as h5py
import numpy as np
import os

## Set Parameters

In [4]:
np.random.seed(98)
n_samples = 20
n_dim = 3

## Create Toy Data
### numpy arrays

In [5]:
# numpy arrays
X = np.random.uniform(low=-5, high=5, size=(n_samples, n_dim))

### hdf5 files

In [6]:
# when working on colab, google drive can be used to save and read data
from google.colab import drive
drive.mount('/content/drive')

# depending on the structure of your google drive, you might want to choose a different dataset path
dataset_path = '/content/drive/MyDrive/'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [7]:
# hdf5 files using h5py
X_file = f'train.hdf5'

with h5py.File(os.path.join(dataset_path, f"{X_file}"), 'w') as f:
    f.create_dataset("X", data=X)

# open the hdf5 file for use
X_data = h5py.File(os.path.join(dataset_path, X_file), 'r')

## Scikit-learn


In [8]:
pca_sk = PCA_sk(n_components=2)

pca_sk.fit(X)
pca_sk.transform(X)

array([[-1.58473104,  0.79893721],
       [-0.92822381,  0.28984871],
       [ 1.80687758,  0.74262492],
       [ 4.08544446,  1.71724538],
       [-3.95675763, -3.44066341],
       [-4.43290221, -2.36003492],
       [-4.27286936, -2.0032996 ],
       [-1.62268984,  5.66375729],
       [ 6.15953168,  0.132802  ],
       [-5.54501202,  2.07147302],
       [-3.02132808, -0.12196357],
       [-1.30904908, -3.21932466],
       [ 2.49030777,  2.06508366],
       [-5.72565927,  3.44920117],
       [ 4.07681933, -1.86069684],
       [ 5.19637105,  3.06962547],
       [ 3.17831714, -2.71930587],
       [-0.36333476,  0.62327764],
       [ 1.06274721, -3.83762988],
       [ 4.70614087, -1.0609577 ]])

## SIMBSIG
### Using numpy arrays and CPU only
SIMBSIG can be used very similar to scikit-learn. In an existing workflow using scikit-learn, which may be on the verge of exceeding runtime or memory requirements, this allows a seamless transition to SIMBSIG. Notice that when using different methods for PCA, the principal components may have a different sign.


In [9]:
pca = PCA(n_components=2)

pca.fit(X)
pca.transform(X)

array([[-1.5847305 , -0.7989384 ],
       [-0.92822325, -0.28985062],
       [ 1.8068776 , -0.74262506],
       [ 4.0854445 , -1.7172444 ],
       [-3.956758  ,  3.4406643 ],
       [-4.432902  ,  2.360035  ],
       [-4.272869  ,  2.0032992 ],
       [-1.6226901 , -5.663756  ],
       [ 6.1595316 , -0.13280128],
       [-5.5450115 , -2.0714736 ],
       [-3.0213275 ,  0.12196311],
       [-1.3090496 ,  3.2193263 ],
       [ 2.4903078 , -2.0650828 ],
       [-5.725659  , -3.4492009 ],
       [ 4.07682   ,  1.8606962 ],
       [ 5.1963706 , -3.0696251 ],
       [ 3.1783166 ,  2.7193084 ],
       [-0.36333445, -0.6232783 ],
       [ 1.0627475 ,  3.8376284 ],
       [ 4.7061405 ,  1.0609584 ]], dtype=float32)

### Using hdf5 files and CPU only
If saving the entire data at once in the computer memory using numpy arrays is not reasonable anymore, the hdf5 file format can help. SIMBSIG can use data in hdf5 files, by setting the `mode` argument to `cpu`

In [10]:
pca_hdf5 = PCA(n_components=2, mode='hdf5')

pca_hdf5.fit(X_data)
pca_hdf5.transform(X_data)

array([[-1.5847305 , -0.7989333 ],
       [-0.9282231 , -0.28984198],
       [ 1.806878  , -0.742624  ],
       [ 4.0854445 , -1.7172475 ],
       [-3.9567585 ,  3.4406624 ],
       [-4.432903  ,  2.3600357 ],
       [-4.2728696 ,  2.0033002 ],
       [-1.6226912 , -5.6637616 ],
       [ 6.1595325 , -0.1328026 ],
       [-5.5450125 , -2.0714726 ],
       [-3.0213282 ,  0.12196533],
       [-1.3090498 ,  3.2193189 ],
       [ 2.490308  , -2.0650868 ],
       [-5.725661  , -3.449202  ],
       [ 4.076821  ,  1.8607014 ],
       [ 5.1963716 , -3.0696251 ],
       [ 3.178317  ,  2.719299  ],
       [-0.3633345 , -0.62327504],
       [ 1.0627483 ,  3.8376338 ],
       [ 4.706142  ,  1.060957  ]], dtype=float32)

### Using GPU acceleration
If data gets big, the execution time becomes an issue. SIMBSIG features GPU acceleration, by setting the `device` argument to `gpu`. This works with both inputs, numpy arrays and hdf5 files.

In [11]:
pca_hdf5 = PCA(n_components=2, mode='hdf5', device='gpu')

pca_hdf5.fit(X_data)
pca_hdf5.transform(X_data)

array([[ 1.5847311 ,  0.7989383 ],
       [ 0.928224  ,  0.2898505 ],
       [-1.8068775 ,  0.74262565],
       [-4.085444  ,  1.7172455 ],
       [ 3.956757  , -3.4406655 ],
       [ 4.4329014 , -2.3600361 ],
       [ 4.272869  , -2.0033004 ],
       [ 1.6226904 ,  5.663757  ],
       [-6.159531  ,  0.1328026 ],
       [ 5.545012  ,  2.0714726 ],
       [ 3.0213277 , -0.12196371],
       [ 1.3090483 , -3.219327  ],
       [-2.4903078 ,  2.0650835 ],
       [ 5.7256594 ,  3.4492002 ],
       [-4.0768194 , -1.8606951 ],
       [-5.1963696 ,  3.0696268 ],
       [-3.1783178 , -2.719308  ],
       [ 0.3633349 ,  0.62327844],
       [-1.0627475 , -3.8376286 ],
       [-4.706141  , -1.0609574 ]], dtype=float32)